---
- hosts: prometheus 
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: true
    - name: start nginx
      service:
        name: nginx
        state: started
